---

- name: Download nodeJS Script
  get_url:
    url: https://deb.nodesource.com/setup_10.x
    dest: /tmp/node10.sh
    mode: 0755

- name: Add NodeJS repository
  command: bash /tmp/node10.sh
  
- name: Make sure NPM and NodeJS installed
  apt: 
    pkg:
      - nodejs
    state: present

- name: Install Odoo dependencies (npm)
  npm:  name={{ item.name }}
        version={{ item.version }}
        global=yes
  with_items: "{{ odoo_npm_packages | default([]) }}"
  when: odoo_version|int < 13

- name: Install Odoo dependencies (npm)
  npm:  name={{ item.name }}
        global=yes
  with_items: "{{ odoo_npm_packages | default([]) }}"
  when: odoo_version|int > 12
