---

- name: Install Odoo dependencies
  apt:  pkg={{ odoo_debian_packages }}
        state=present
        update_cache={{ odoo_apt_update_cache }}
        cache_valid_time={{ odoo_apt_cache_valid_time }}
  tags:
    - odoo_packages

- name: Install Odoo dependencies (PyPi)
  pip: name={{ item }}
  with_items: "{{ odoo_pypi_packages }}"
  tags:
    - odoo_packages

- name: Import pip requirements files
  become: yes
  become_user: "{{ odoo_user }}"
  copy:
    src: "files/requirements_Ubuntu-18_Odoo-12.txt" 
    dest: "/home/{{ odoo_user }}/odoo/server/requirements.txt"

- name: Install Odoo Requirements (PyPi)
  pip:
   requirements: "{{ odoo_requirements }}"
  when: odoo_version | int > 11
  tags:
    - odoo_packages

- import_tasks: config.yml
  tags:
    - odoo_config
