---
- name: PostgreSQL - Add the Odoo user
  become: yes
  become_user: postgres
  postgresql_user: name={{ odoo_config_db_user }}
                    role_attr_flags={{ odoo_postgresql_user_role_attr }}
  when: odoo_postgresql_set_user

- name: PostgreSQL - Set the Odoo user password
  become: yes
  become_user: postgres
  postgresql_user: name={{ odoo_config_db_user }}
                    password={{ odoo_config_db_passwd }}
  when: odoo_config_db_passwd is defined and odoo_config_db_passwd
        and odoo_postgresql_set_user

- name: PostgreSQL - Activate some extensions on the 'template1' database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: "{{ item }}"
    db: template1
  with_items: "{{ odoo_postgresql_extensions }}"