---

- name: Install Odoo dependencies
  apt:  pkg={{ item }}
        state=present
        update_cache={{ odoo_apt_update_cache }}
        cache_valid_time={{ odoo_apt_cache_valid_time }}
  with_items: "{{ odoo_debian_packages }}"
  tags:
    - odoo_packages

- name: Install Odoo dependencies (PyPi)
  pip: name={{ item }}
  with_items: "{{ odoo_pypi_packages }}"
  tags:
    - odoo_packages

- name: Install Odoo Requirements (PyPi)
  pip:
   requirements: "{{ odoo_requirements }}"
  when: odoo_version | int > 11
  tags:
    - odoo_packages

- import_tasks: config.yml
  tags:
    - odoo_config
